# Generated by Django 5.2.5 on 2025-08-30 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the exam', max_length=255)),
                ('start_time', models.DateTimeField(help_text='The time the exam starts (timezone-aware)')),
                ('end_time', models.DateTimeField(help_text='The time the exam ends (timezone-aware)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='A cryptographically secure, unique token (e.g., UUID4 or equivalent)', max_length=36, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text='Indicates if the token has been consumed')),
                ('valid_from', models.DateTimeField(help_text="Start of the token's validity window (timezone-aware)")),
                ('valid_until', models.DateTimeField(help_text="End of the token's validity window (timezone-aware)")),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp for token creation')),
                ('used_at', models.DateTimeField(blank=True, help_text='When this token was consumed', null=True)),
                ('exam', models.ForeignKey(help_text='Links the token to a specific exam', on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='exams.exam')),
                ('student', models.ForeignKey(help_text='Links the token to a specific student', on_delete=django.db.models.deletion.CASCADE, related_name='exam_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Access Token',
                'verbose_name_plural': 'Exam Access Tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='exam_token_idx'), models.Index(fields=['valid_until'], name='exam_token_valid_until_idx'), models.Index(fields=['is_used'], name='exam_token_is_used_idx'), models.Index(fields=['exam', 'student'], name='exam_student_idx')],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
